version: 1
labels:
  - label: "Tests - C# Library"
    files:
      - "src/Record/Record.Test/.*"
  - label: "Nuget publish - C# Library"
    files:
      - "src/Record/Record.Model/.*"
  - label: "Workflows"
    files:
      - ".*yml"
  - label: "SHACL"
    files:
      - ".*shacl"
  - label: "Schema"
    files:
      - "schema/.*"