trigger:
  branches:
    include:
      - test
      - prod
  paths:
    include:
      - 'src/Record/Record.Model'

pr: none

pool: 
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  isTest: $[eq(variables['Build.SourceBranch'], 'refs/heads/test')]
  isProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/prod')]

steps:

  - task: UseDotNet@2
    inputs:
      version: '6.0.x'

  - script: dotnet --version
    displayName: 'Check .Net version'

  - script: dotnet nuget locals all -c
    displayName: 'Clearing nugets cache packages'
  
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'src/Record/Record.Model/Records.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables.isTest, 'true'))
    inputs:
      command: 'pack'
      packagesToPack: 'src/Record/Record.Model/Records.csproj'
      includeReferencedProjects: true
      buildProperties: 'ReleaseType="-prerelease";description="A library for using records."'
      versioningScheme: 'off'
  
  - task: DotNetCoreCLI@2
    condition: and(succeeded(), eq(variables.isProd, 'true'))
    inputs:
      command: 'pack'
      packagesToPack: 'src/Record/Record.Model/Records.csproj'
      includeReferencedProjects: true
      buildProperties: 'description="A library for using records.'  
      versioningScheme: 'off'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'internal'
      publishVstsFeed: '6503fe8e-34c7-4b66-902f-892c4bef4b45/de8f8c5a-eef9-4608-8ecb-e80e83354392'
      allowPackageConflicts: true
